"""Corpus conversion report generation."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import tempfile
from typing import Callable

from pic_fixture_converters import openfisca_to_pic, policyengine_to_pic


def build_report(repo_root: Path) -> str:
    corpus_root = repo_root / "converters" / "fixtures" / "corpus"
    rows: list[dict[str, str | int]] = []
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        for dialect, converter in [
            ("openfisca", openfisca_to_pic),
            ("policyengine", policyengine_to_pic),
        ]:
            for source in sorted((corpus_root / dialect).glob("*.yaml")):
                rows.append(_convert_one(repo_root, tmp_path, dialect, source, converter))
    return _render_markdown(rows)


def _convert_one(
    repo_root: Path,
    tmp_path: Path,
    dialect: str,
    source: Path,
    converter: Callable[[Path], list[dict]],
) -> dict[str, str | int]:
    try:
        fixtures = converter(source)
        for index, fixture in enumerate(fixtures, start=1):
            output = tmp_path / f"{dialect}-{source.stem}-{index}.json"
            output.write_text(json.dumps(fixture, indent=2, sort_keys=True), encoding="utf-8")
            _pic_validate(repo_root, output)
        status = "converted"
        reason = ""
        cases = sum(len(fixture["cases"]) for fixture in fixtures)
    except Exception as exc:  # noqa: BLE001 - report must classify all corpus outcomes.
        status = "rejected"
        reason = exc.__class__.__name__ + ": " + str(exc)
        cases = 0
    return {
        "dialect": dialect,
        "file": str(source.relative_to(repo_root / "converters" / "fixtures" / "corpus")),
        "status": status,
        "cases": cases,
        "reason": reason,
    }


def _pic_validate(repo_root: Path, path: Path) -> None:
    command = [str(repo_root / "contracts" / "tools" / ".venv" / "bin" / "pic-validate"), str(path)]
    subprocess.run(command, cwd=repo_root, check=True, capture_output=True, text=True)


def _render_markdown(rows: list[dict[str, str | int]]) -> str:
    total = len(rows)
    converted = sum(1 for row in rows if row["status"] == "converted")
    rejected = total - converted
    rate = (converted / total * 100) if total else 0
    lines = [
        "# Fixture Converter Corpus Report",
        "",
        "Generated by `python -m pic_fixture_converters.corpus_report`.",
        "",
        "## Summary",
        "",
        f"- Total files: {total}",
        f"- Converted: {converted}",
        f"- Rejected: {rejected}",
        f"- Clean conversion rate: {rate:.1f}%",
        "",
        "## Files",
        "",
        "| Dialect | File | Status | Cases | Reason |",
        "|---|---|---|---:|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['dialect']} | `{row['file']}` | {row['status']} | "
            f"{row['cases']} | {row['reason']} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--output", type=Path, default=None)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    repo_root = args.repo_root.resolve()
    output = args.output or repo_root / "converters" / "fixtures" / "corpus" / "REPORT.md"
    report = build_report(repo_root)
    if args.check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != report:
            print(f"Corpus report is stale: {output}")
            return 1
        return 0
    output.write_text(report, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
